package com.east.logistics.dao;

import com.east.logistics.entity.Customer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    Customer selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customer record);

    int count();

    List<Customer> selectVague(@Param("cName") String cName, @Param("cJob") String cJob,@Param("cAddress") String cAddress,@Param("cPhone") String cPhone, @Param("sId") Integer sId,@Param("cBillnums") Integer cBillnums,@Param("tId") Integer tId,@Param("cSend") Integer cSend);

    int countVague(@Param("cName") String cName, @Param("cJob") String cJob,@Param("cAddress") String cAddress,@Param("cPhone") String cPhone, @Param("sId") Integer sId,@Param("cBillnums") Integer cBillnums,@Param("tId") Integer tId,@Param("cSend") Integer cSend);


}