package com.east.logistics.dao;

import com.east.logistics.entity.Report;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    Report selectByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    List<Report> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Report record);

    /**
     * 查询所有数据
     * @return
     */
    int count();

    List<Report> selectVague(@Param("rName") String rName,@Param("sId") Integer sId,@Param("cId") Integer cId,@Param("rStatisticstime") String rStatisticstime,@Param("rCreatetime") Timestamp rCreatetime, @Param("rStatus") String rStatus);

    int countVague(@Param("rName") String rName,@Param("sId") Integer sId,@Param("cId") Integer cId,@Param("rStatisticstime") String rStatisticstime,@Param("rCreatetime") Timestamp rCreatetime ,@Param("rStatus") String rStatus);

}