package com.east.logistics.dao;

import com.east.logistics.entity.Staff;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    Staff selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    List<Staff> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Staff record);


    /**
     * 查询所有数据
     * @return
     */
    int count();

    List<Staff> selectVague(@Param("sName") String dName,@Param("sPhone") String dPhone,@Param("sSex") String dSex,@Param("sAccount") String dAccount, @Param("sPassword") String dPassword,@Param("nId") Integer nId,@Param("dIn") Integer dIn,@Param("dOut") Integer dOut);

    int countVague(@Param("sName") String dName,@Param("sPhone") String dPhone,@Param("sSex") String dSex,@Param("sAccount") String dAccount, @Param("sPassword") String dPassword,@Param("nId") Integer nId,@Param("dIn") Integer dIn,@Param("dOut") Integer dOut);
    /**
     * 根据手机号码获取信息
     * @param phone
     * @return
     */
    Staff yzm(@Param("phone") String phone);

    //修改密码
    int updatePassword(@Param("password") String password, @Param("dId") int dId);
}