package com.east.logistics.dao;

import com.east.logistics.entity.Waybill;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WaybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int insert(Waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    Waybill selectByPrimaryKey(Integer wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    List<Waybill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Waybill record);

    /**
     * 查询所有数据
     * @return
     */
    int count();
    //根据订单状态查询、订单编号、联系人号码查询
    List<Waybill> selectStart(@Param("w_status") String wStatus, @Param("w_id") Integer wId,@Param("c_id") Integer cid,@Param("w_sphone") String wSphone,@Param("w_intime") Integer wIntime,@Param("w_outtime") Integer wOuttime,@Param("w_price") Double wPrice,@Param("w_saddress") String wSaddress,@Param("w_raddress") String wRaddress,@Param("w_rphone") String wRphone,@Param("s_inid") Integer sInid,@Param("s_outid") Integer sOutid);
    //根据订单状态查询、订单编号、联系人号码查询
    int countStart(@Param("w_status") String wStatus, @Param("w_id") Integer wId,@Param("c_id") Integer cid,@Param("w_sphone") String wSphone,@Param("w_intime") Integer wIntime,@Param("w_outtime") Integer wOuttime,@Param("w_price") Double wPrice,@Param("w_saddress") String wSaddress,@Param("w_raddress") String wRaddress,@Param("w_rphone") String wRphone,@Param("s_inid") Integer sInid,@Param("s_outid") Integer sOutid);

    int countType(@Param("w_intype") String wIntype,@Param("c_id") Integer cId,@Param("s_inId")  Integer sInid);

    //订单号、订单状态、完成时间
    int updateSet(@Param("w_id") Integer wId, @Param("w_status") String wStatus,@Param("w_outtime") Integer wOuttime);
}