package com.east.logistics.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbg.generated
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_account
     *
     * @mbg.generated
     */
    private String aAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_password
     *
     * @mbg.generated
     */
    private String aPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_type
     *
     * @mbg.generated
     */
    private String aType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_power
     *
     * @mbg.generated
     */
    private Byte aPower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_name
     *
     * @mbg.generated
     */
    private String aName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_sex
     *
     * @mbg.generated
     */
    private String aSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_phone
     *
     * @mbg.generated
     */
    private String aPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbg.generated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbg.generated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_account
     *
     * @return the value of admin.a_account
     *
     * @mbg.generated
     */
    public String getaAccount() {
        return aAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_account
     *
     * @param aAccount the value for admin.a_account
     *
     * @mbg.generated
     */
    public void setaAccount(String aAccount) {
        this.aAccount = aAccount == null ? null : aAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_password
     *
     * @return the value of admin.a_password
     *
     * @mbg.generated
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_password
     *
     * @param aPassword the value for admin.a_password
     *
     * @mbg.generated
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword == null ? null : aPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_type
     *
     * @return the value of admin.a_type
     *
     * @mbg.generated
     */
    public String getaType() {
        return aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_type
     *
     * @param aType the value for admin.a_type
     *
     * @mbg.generated
     */
    public void setaType(String aType) {
        this.aType = aType == null ? null : aType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_power
     *
     * @return the value of admin.a_power
     *
     * @mbg.generated
     */
    public Byte getaPower() {
        return aPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_power
     *
     * @param aPower the value for admin.a_power
     *
     * @mbg.generated
     */
    public void setaPower(Byte aPower) {
        this.aPower = aPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_name
     *
     * @return the value of admin.a_name
     *
     * @mbg.generated
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_name
     *
     * @param aName the value for admin.a_name
     *
     * @mbg.generated
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_sex
     *
     * @return the value of admin.a_sex
     *
     * @mbg.generated
     */
    public String getaSex() {
        return aSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_sex
     *
     * @param aSex the value for admin.a_sex
     *
     * @mbg.generated
     */
    public void setaSex(String aSex) {
        this.aSex = aSex == null ? null : aSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_phone
     *
     * @return the value of admin.a_phone
     *
     * @mbg.generated
     */
    public String getaPhone() {
        return aPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_phone
     *
     * @param aPhone the value for admin.a_phone
     *
     * @mbg.generated
     */
    public void setaPhone(String aPhone) {
        this.aPhone = aPhone == null ? null : aPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.n_id
     *
     * @return the value of admin.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.n_id
     *
     * @param nId the value for admin.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }
}