package com.east.logistics.entity;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_job
     *
     * @mbg.generated
     */
    private String cJob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_address
     *
     * @mbg.generated
     */
    private String cAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_phone
     *
     * @mbg.generated
     */
    private String cPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_billnums
     *
     * @mbg.generated
     */
    private Integer cBillnums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_send
     *
     * @mbg.generated
     */
    private Integer cSend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_id
     *
     * @return the value of customer.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_id
     *
     * @param cId the value for customer.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_name
     *
     * @return the value of customer.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_name
     *
     * @param cName the value for customer.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_job
     *
     * @return the value of customer.c_job
     *
     * @mbg.generated
     */
    public String getcJob() {
        return cJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_job
     *
     * @param cJob the value for customer.c_job
     *
     * @mbg.generated
     */
    public void setcJob(String cJob) {
        this.cJob = cJob == null ? null : cJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_address
     *
     * @return the value of customer.c_address
     *
     * @mbg.generated
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_address
     *
     * @param cAddress the value for customer.c_address
     *
     * @mbg.generated
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_phone
     *
     * @return the value of customer.c_phone
     *
     * @mbg.generated
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_phone
     *
     * @param cPhone the value for customer.c_phone
     *
     * @mbg.generated
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.s_id
     *
     * @return the value of customer.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.s_id
     *
     * @param sId the value for customer.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_billnums
     *
     * @return the value of customer.c_billnums
     *
     * @mbg.generated
     */
    public Integer getcBillnums() {
        return cBillnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_billnums
     *
     * @param cBillnums the value for customer.c_billnums
     *
     * @mbg.generated
     */
    public void setcBillnums(Integer cBillnums) {
        this.cBillnums = cBillnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.t_id
     *
     * @return the value of customer.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.t_id
     *
     * @param tId the value for customer.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_send
     *
     * @return the value of customer.c_send
     *
     * @mbg.generated
     */
    public Integer getcSend() {
        return cSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_send
     *
     * @param cSend the value for customer.c_send
     *
     * @mbg.generated
     */
    public void setcSend(Integer cSend) {
        this.cSend = cSend;
    }
}