package com.east.logistics.entity;

import java.math.BigDecimal;

public class Locations {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.add_name
     *
     * @mbg.generated
     */
    private String addName;

    public String getEndIp() {
        return endIp;
    }

    public void setEndIp(String endIp) {
        this.endIp = endIp;
    }

    private String endIp
            ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.add_ip
     *
     * @mbg.generated
     */
    private String addIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.pei_yong
     *
     * @mbg.generated
     */
    private String peiYong;

    public String getEndName() {
        return endName;
    }

    public void setEndName(String endName) {
        this.endName = endName;
    }

    private String endName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locations.pei_yongs
     *
     * @mbg.generated
     */
    private String peiYongs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.id
     *
     * @return the value of locations.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    private BigDecimal price;

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.id
     *
     * @param id the value for locations.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.add_name
     *
     * @return the value of locations.add_name
     * @mbg.generated
     */
    public String getAddName() {
        return addName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.add_name
     *
     * @param addName the value for locations.add_name
     * @mbg.generated
     */
    public void setAddName(String addName) {
        this.addName = addName == null ? null : addName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.add_ip
     *
     * @return the value of locations.add_ip
     * @mbg.generated
     */
    public String getAddIp() {
        return addIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.add_ip
     *
     * @param addIp the value for locations.add_ip
     * @mbg.generated
     */
    public void setAddIp(String addIp) {
        this.addIp = addIp == null ? null : addIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.type
     *
     * @return the value of locations.type
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.type
     *
     * @param type the value for locations.type
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.pei_yong
     *
     * @return the value of locations.pei_yong
     * @mbg.generated
     */
    public String getPeiYong() {
        return peiYong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.pei_yong
     *
     * @param peiYong the value for locations.pei_yong
     * @mbg.generated
     */
    public void setPeiYong(String peiYong) {
        this.peiYong = peiYong == null ? null : peiYong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locations.pei_yongs
     *
     * @return the value of locations.pei_yongs
     * @mbg.generated
     */
    public String getPeiYongs() {
        return peiYongs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locations.pei_yongs
     *
     * @param peiYongs the value for locations.pei_yongs
     * @mbg.generated
     */
    public void setPeiYongs(String peiYongs) {
        this.peiYongs = peiYongs == null ? null : peiYongs.trim();
    }
}