package com.east.logistics.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.r_id
     *
     * @mbg.generated
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.r_name
     *
     * @mbg.generated
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.r_statisticstime
     *
     * @mbg.generated
     */
    private String rStatisticstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.r_createtime
     *
     * @mbg.generated
     */
    private Date rCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.r_money
     *
     * @mbg.generated
     */
    private BigDecimal rMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.r_status
     *
     * @mbg.generated
     */
    private String rStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.r_id
     *
     * @return the value of report.r_id
     *
     * @mbg.generated
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.r_id
     *
     * @param rId the value for report.r_id
     *
     * @mbg.generated
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.r_name
     *
     * @return the value of report.r_name
     *
     * @mbg.generated
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.r_name
     *
     * @param rName the value for report.r_name
     *
     * @mbg.generated
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.s_id
     *
     * @return the value of report.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.s_id
     *
     * @param sId the value for report.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.c_id
     *
     * @return the value of report.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.c_id
     *
     * @param cId the value for report.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.r_statisticstime
     *
     * @return the value of report.r_statisticstime
     *
     * @mbg.generated
     */
    public String getrStatisticstime() {
        return rStatisticstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.r_statisticstime
     *
     * @param rStatisticstime the value for report.r_statisticstime
     *
     * @mbg.generated
     */
    public void setrStatisticstime(String rStatisticstime) {
        this.rStatisticstime = rStatisticstime == null ? null : rStatisticstime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.r_createtime
     *
     * @return the value of report.r_createtime
     *
     * @mbg.generated
     */
    public Date getrCreatetime() {
        return rCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.r_createtime
     *
     * @param rCreatetime the value for report.r_createtime
     *
     * @mbg.generated
     */
    public void setrCreatetime(Date rCreatetime) {
        this.rCreatetime = rCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.r_money
     *
     * @return the value of report.r_money
     *
     * @mbg.generated
     */
    public BigDecimal getrMoney() {
        return rMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.r_money
     *
     * @param rMoney the value for report.r_money
     *
     * @mbg.generated
     */
    public void setrMoney(BigDecimal rMoney) {
        this.rMoney = rMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.r_status
     *
     * @return the value of report.r_status
     *
     * @mbg.generated
     */
    public String getrStatus() {
        return rStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.r_status
     *
     * @param rStatus the value for report.r_status
     *
     * @mbg.generated
     */
    public void setrStatus(String rStatus) {
        this.rStatus = rStatus == null ? null : rStatus.trim();
    }
}