package com.east.logistics.entity;

public class Staff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_sex
     *
     * @mbg.generated
     */
    private String sSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_account
     *
     * @mbg.generated
     */
    private String sAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_password
     *
     * @mbg.generated
     */
    private String sPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_phone
     *
     * @mbg.generated
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_in
     *
     * @mbg.generated
     */
    private Integer sIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_out
     *
     * @mbg.generated
     */
    private Integer sOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.s_photo
     *
     * @mbg.generated
     */
    private byte[] sPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_id
     *
     * @return the value of staff.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_id
     *
     * @param sId the value for staff.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_name
     *
     * @return the value of staff.s_name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_name
     *
     * @param sName the value for staff.s_name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_sex
     *
     * @return the value of staff.s_sex
     *
     * @mbg.generated
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_sex
     *
     * @param sSex the value for staff.s_sex
     *
     * @mbg.generated
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_account
     *
     * @return the value of staff.s_account
     *
     * @mbg.generated
     */
    public String getsAccount() {
        return sAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_account
     *
     * @param sAccount the value for staff.s_account
     *
     * @mbg.generated
     */
    public void setsAccount(String sAccount) {
        this.sAccount = sAccount == null ? null : sAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_password
     *
     * @return the value of staff.s_password
     *
     * @mbg.generated
     */
    public String getsPassword() {
        return sPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_password
     *
     * @param sPassword the value for staff.s_password
     *
     * @mbg.generated
     */
    public void setsPassword(String sPassword) {
        this.sPassword = sPassword == null ? null : sPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.n_id
     *
     * @return the value of staff.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.n_id
     *
     * @param nId the value for staff.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_phone
     *
     * @return the value of staff.s_phone
     *
     * @mbg.generated
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_phone
     *
     * @param sPhone the value for staff.s_phone
     *
     * @mbg.generated
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_in
     *
     * @return the value of staff.s_in
     *
     * @mbg.generated
     */
    public Integer getsIn() {
        return sIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_in
     *
     * @param sIn the value for staff.s_in
     *
     * @mbg.generated
     */
    public void setsIn(Integer sIn) {
        this.sIn = sIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_out
     *
     * @return the value of staff.s_out
     *
     * @mbg.generated
     */
    public Integer getsOut() {
        return sOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_out
     *
     * @param sOut the value for staff.s_out
     *
     * @mbg.generated
     */
    public void setsOut(Integer sOut) {
        this.sOut = sOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.s_photo
     *
     * @return the value of staff.s_photo
     *
     * @mbg.generated
     */
    public byte[] getsPhoto() {
        return sPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.s_photo
     *
     * @param sPhoto the value for staff.s_photo
     *
     * @mbg.generated
     */
    public void setsPhoto(byte[] sPhoto) {
        this.sPhoto = sPhoto;
    }
}