package com.east.logistics.entity;

import java.math.BigDecimal;

public class Template {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_name
     *
     * @mbg.generated
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_type
     *
     * @mbg.generated
     */
    private String tType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_customer
     *
     * @mbg.generated
     */
    private String tCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_area
     *
     * @mbg.generated
     */
    private String tArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_weight
     *
     * @mbg.generated
     */
    private Float tWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_price
     *
     * @mbg.generated
     */
    private BigDecimal tPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_addweight
     *
     * @mbg.generated
     */
    private Float tAddweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.t_addprice
     *
     * @mbg.generated
     */
    private BigDecimal tAddprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_id
     *
     * @return the value of template.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_id
     *
     * @param tId the value for template.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_name
     *
     * @return the value of template.t_name
     *
     * @mbg.generated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_name
     *
     * @param tName the value for template.t_name
     *
     * @mbg.generated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_type
     *
     * @return the value of template.t_type
     *
     * @mbg.generated
     */
    public String gettType() {
        return tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_type
     *
     * @param tType the value for template.t_type
     *
     * @mbg.generated
     */
    public void settType(String tType) {
        this.tType = tType == null ? null : tType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.s_id
     *
     * @return the value of template.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.s_id
     *
     * @param sId the value for template.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_customer
     *
     * @return the value of template.t_customer
     *
     * @mbg.generated
     */
    public String gettCustomer() {
        return tCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_customer
     *
     * @param tCustomer the value for template.t_customer
     *
     * @mbg.generated
     */
    public void settCustomer(String tCustomer) {
        this.tCustomer = tCustomer == null ? null : tCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_area
     *
     * @return the value of template.t_area
     *
     * @mbg.generated
     */
    public String gettArea() {
        return tArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_area
     *
     * @param tArea the value for template.t_area
     *
     * @mbg.generated
     */
    public void settArea(String tArea) {
        this.tArea = tArea == null ? null : tArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_weight
     *
     * @return the value of template.t_weight
     *
     * @mbg.generated
     */
    public Float gettWeight() {
        return tWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_weight
     *
     * @param tWeight the value for template.t_weight
     *
     * @mbg.generated
     */
    public void settWeight(Float tWeight) {
        this.tWeight = tWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_price
     *
     * @return the value of template.t_price
     *
     * @mbg.generated
     */
    public BigDecimal gettPrice() {
        return tPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_price
     *
     * @param tPrice the value for template.t_price
     *
     * @mbg.generated
     */
    public void settPrice(BigDecimal tPrice) {
        this.tPrice = tPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_addweight
     *
     * @return the value of template.t_addweight
     *
     * @mbg.generated
     */
    public Float gettAddweight() {
        return tAddweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_addweight
     *
     * @param tAddweight the value for template.t_addweight
     *
     * @mbg.generated
     */
    public void settAddweight(Float tAddweight) {
        this.tAddweight = tAddweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.t_addprice
     *
     * @return the value of template.t_addprice
     *
     * @mbg.generated
     */
    public BigDecimal gettAddprice() {
        return tAddprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.t_addprice
     *
     * @param tAddprice the value for template.t_addprice
     *
     * @mbg.generated
     */
    public void settAddprice(BigDecimal tAddprice) {
        this.tAddprice = tAddprice;
    }
}