package com.east.logistics.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Waybill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_id
     *
     * @mbg.generated
     */
    private Integer wId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_status
     *
     * @mbg.generated
     */
    private String wStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_info
     *
     * @mbg.generated
     */
    private String wInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_note
     *
     * @mbg.generated
     */
    private String wNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_weight
     *
     * @mbg.generated
     */
    private Float wWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_price
     *
     * @mbg.generated
     */
    private BigDecimal wPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_type
     *
     * @mbg.generated
     */
    private String wType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_inid
     *
     * @mbg.generated
     */
    private Integer sInid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_intime
     *
     * @mbg.generated
     */
    private Date wIntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_intype
     *
     * @mbg.generated
     */
    private String wIntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_outid
     *
     * @mbg.generated
     */
    private Integer sOutid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_outtime
     *
     * @mbg.generated
     */
    private Date wOuttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_outproof
     *
     * @mbg.generated
     */
    private String wOutproof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_sname
     *
     * @mbg.generated
     */
    private String wSname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_sphone
     *
     * @mbg.generated
     */
    private String wSphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_spro
     *
     * @mbg.generated
     */
    private String wSpro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_scity
     *
     * @mbg.generated
     */
    private String wScity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_scounty
     *
     * @mbg.generated
     */
    private String wScounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_saddress
     *
     * @mbg.generated
     */
    private String wSaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_rname
     *
     * @mbg.generated
     */
    private String wRname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_rphone
     *
     * @mbg.generated
     */
    private String wRphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_rpro
     *
     * @mbg.generated
     */
    private String wRpro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_rcity
     *
     * @mbg.generated
     */
    private String wRcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_rcounty
     *
     * @mbg.generated
     */
    private String wRcounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_raddress
     *
     * @mbg.generated
     */
    private String wRaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_id
     *
     * @return the value of waybill.w_id
     *
     * @mbg.generated
     */
    public Integer getwId() {
        return wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_id
     *
     * @param wId the value for waybill.w_id
     *
     * @mbg.generated
     */
    public void setwId(Integer wId) {
        this.wId = wId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_status
     *
     * @return the value of waybill.w_status
     *
     * @mbg.generated
     */
    public String getwStatus() {
        return wStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_status
     *
     * @param wStatus the value for waybill.w_status
     *
     * @mbg.generated
     */
    public void setwStatus(String wStatus) {
        this.wStatus = wStatus == null ? null : wStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_info
     *
     * @return the value of waybill.w_info
     *
     * @mbg.generated
     */
    public String getwInfo() {
        return wInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_info
     *
     * @param wInfo the value for waybill.w_info
     *
     * @mbg.generated
     */
    public void setwInfo(String wInfo) {
        this.wInfo = wInfo == null ? null : wInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.c_id
     *
     * @return the value of waybill.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.c_id
     *
     * @param cId the value for waybill.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_note
     *
     * @return the value of waybill.w_note
     *
     * @mbg.generated
     */
    public String getwNote() {
        return wNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_note
     *
     * @param wNote the value for waybill.w_note
     *
     * @mbg.generated
     */
    public void setwNote(String wNote) {
        this.wNote = wNote == null ? null : wNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_weight
     *
     * @return the value of waybill.w_weight
     *
     * @mbg.generated
     */
    public Float getwWeight() {
        return wWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_weight
     *
     * @param wWeight the value for waybill.w_weight
     *
     * @mbg.generated
     */
    public void setwWeight(Float wWeight) {
        this.wWeight = wWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_price
     *
     * @return the value of waybill.w_price
     *
     * @mbg.generated
     */
    public BigDecimal getwPrice() {
        return wPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_price
     *
     * @param wPrice the value for waybill.w_price
     *
     * @mbg.generated
     */
    public void setwPrice(BigDecimal wPrice) {
        this.wPrice = wPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_type
     *
     * @return the value of waybill.w_type
     *
     * @mbg.generated
     */
    public String getwType() {
        return wType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_type
     *
     * @param wType the value for waybill.w_type
     *
     * @mbg.generated
     */
    public void setwType(String wType) {
        this.wType = wType == null ? null : wType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_inid
     *
     * @return the value of waybill.s_inid
     *
     * @mbg.generated
     */
    public Integer getsInid() {
        return sInid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_inid
     *
     * @param sInid the value for waybill.s_inid
     *
     * @mbg.generated
     */
    public void setsInid(Integer sInid) {
        this.sInid = sInid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_intime
     *
     * @return the value of waybill.w_intime
     *
     * @mbg.generated
     */
    public Date getwIntime() {
        return wIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_intime
     *
     * @param wIntime the value for waybill.w_intime
     *
     * @mbg.generated
     */
    public void setwIntime(Date wIntime) {
        this.wIntime = wIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_intype
     *
     * @return the value of waybill.w_intype
     *
     * @mbg.generated
     */
    public String getwIntype() {
        return wIntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_intype
     *
     * @param wIntype the value for waybill.w_intype
     *
     * @mbg.generated
     */
    public void setwIntype(String wIntype) {
        this.wIntype = wIntype == null ? null : wIntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_outid
     *
     * @return the value of waybill.s_outid
     *
     * @mbg.generated
     */
    public Integer getsOutid() {
        return sOutid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_outid
     *
     * @param sOutid the value for waybill.s_outid
     *
     * @mbg.generated
     */
    public void setsOutid(Integer sOutid) {
        this.sOutid = sOutid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_outtime
     *
     * @return the value of waybill.w_outtime
     *
     * @mbg.generated
     */
    public Date getwOuttime() {
        return wOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_outtime
     *
     * @param wOuttime the value for waybill.w_outtime
     *
     * @mbg.generated
     */
    public void setwOuttime(Date wOuttime) {
        this.wOuttime = wOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_outproof
     *
     * @return the value of waybill.w_outproof
     *
     * @mbg.generated
     */
    public String getwOutproof() {
        return wOutproof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_outproof
     *
     * @param wOutproof the value for waybill.w_outproof
     *
     * @mbg.generated
     */
    public void setwOutproof(String wOutproof) {
        this.wOutproof = wOutproof == null ? null : wOutproof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_sname
     *
     * @return the value of waybill.w_sname
     *
     * @mbg.generated
     */
    public String getwSname() {
        return wSname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_sname
     *
     * @param wSname the value for waybill.w_sname
     *
     * @mbg.generated
     */
    public void setwSname(String wSname) {
        this.wSname = wSname == null ? null : wSname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_sphone
     *
     * @return the value of waybill.w_sphone
     *
     * @mbg.generated
     */
    public String getwSphone() {
        return wSphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_sphone
     *
     * @param wSphone the value for waybill.w_sphone
     *
     * @mbg.generated
     */
    public void setwSphone(String wSphone) {
        this.wSphone = wSphone == null ? null : wSphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_spro
     *
     * @return the value of waybill.w_spro
     *
     * @mbg.generated
     */
    public String getwSpro() {
        return wSpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_spro
     *
     * @param wSpro the value for waybill.w_spro
     *
     * @mbg.generated
     */
    public void setwSpro(String wSpro) {
        this.wSpro = wSpro == null ? null : wSpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_scity
     *
     * @return the value of waybill.w_scity
     *
     * @mbg.generated
     */
    public String getwScity() {
        return wScity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_scity
     *
     * @param wScity the value for waybill.w_scity
     *
     * @mbg.generated
     */
    public void setwScity(String wScity) {
        this.wScity = wScity == null ? null : wScity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_scounty
     *
     * @return the value of waybill.w_scounty
     *
     * @mbg.generated
     */
    public String getwScounty() {
        return wScounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_scounty
     *
     * @param wScounty the value for waybill.w_scounty
     *
     * @mbg.generated
     */
    public void setwScounty(String wScounty) {
        this.wScounty = wScounty == null ? null : wScounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_saddress
     *
     * @return the value of waybill.w_saddress
     *
     * @mbg.generated
     */
    public String getwSaddress() {
        return wSaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_saddress
     *
     * @param wSaddress the value for waybill.w_saddress
     *
     * @mbg.generated
     */
    public void setwSaddress(String wSaddress) {
        this.wSaddress = wSaddress == null ? null : wSaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_rname
     *
     * @return the value of waybill.w_rname
     *
     * @mbg.generated
     */
    public String getwRname() {
        return wRname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_rname
     *
     * @param wRname the value for waybill.w_rname
     *
     * @mbg.generated
     */
    public void setwRname(String wRname) {
        this.wRname = wRname == null ? null : wRname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_rphone
     *
     * @return the value of waybill.w_rphone
     *
     * @mbg.generated
     */
    public String getwRphone() {
        return wRphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_rphone
     *
     * @param wRphone the value for waybill.w_rphone
     *
     * @mbg.generated
     */
    public void setwRphone(String wRphone) {
        this.wRphone = wRphone == null ? null : wRphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_rpro
     *
     * @return the value of waybill.w_rpro
     *
     * @mbg.generated
     */
    public String getwRpro() {
        return wRpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_rpro
     *
     * @param wRpro the value for waybill.w_rpro
     *
     * @mbg.generated
     */
    public void setwRpro(String wRpro) {
        this.wRpro = wRpro == null ? null : wRpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_rcity
     *
     * @return the value of waybill.w_rcity
     *
     * @mbg.generated
     */
    public String getwRcity() {
        return wRcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_rcity
     *
     * @param wRcity the value for waybill.w_rcity
     *
     * @mbg.generated
     */
    public void setwRcity(String wRcity) {
        this.wRcity = wRcity == null ? null : wRcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_rcounty
     *
     * @return the value of waybill.w_rcounty
     *
     * @mbg.generated
     */
    public String getwRcounty() {
        return wRcounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_rcounty
     *
     * @param wRcounty the value for waybill.w_rcounty
     *
     * @mbg.generated
     */
    public void setwRcounty(String wRcounty) {
        this.wRcounty = wRcounty == null ? null : wRcounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_raddress
     *
     * @return the value of waybill.w_raddress
     *
     * @mbg.generated
     */
    public String getwRaddress() {
        return wRaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_raddress
     *
     * @param wRaddress the value for waybill.w_raddress
     *
     * @mbg.generated
     */
    public void setwRaddress(String wRaddress) {
        this.wRaddress = wRaddress == null ? null : wRaddress.trim();
    }
}